### ISSUE TITLE
Database, Pics, Build

### ISSUE THREAD

**Issue by fervi** [Hello23-Ygopro/ygopro-ka#8]
Hello.

1) I do a project where people will be able to exchange YGOPro decks. Of course I have Yu-Gi-Oh !, but I would like to add DuelMasters. I need a database for this (because YGOPro-DM is compatible with YGOPro-YGO?) And images. Do you have this? :)

2) How to compile it. I tried to follow the instructions + build a YGOPro engine but it crashes
http://meshnet-users.tk/paste/p/hoks/h.txt

**Comment by Hello23-Ygopro** [comment]
> I would like to add DuelMasters

You can, but some cards i still have to fix for playing : 
https://github.com/Hello23-Ygopro/ygopro-dm/issues/6
https://github.com/Hello23-Ygopro/ygopro-dm/issues/8
and i dont know how many bugs are left from other cards i missed..
my advise wud be to leave out the video game-only cards and only add if both players agree, cus theres no official rulings for them and they might not work how their supposed to

> I need a database for this

Theres alot of databases here for DM-01~DM-05 :
https://github.com/Hello23-Ygopro/ygopro-dm/tree/master/expansions

i think they can be merged with a tool or script auto-matically, but i dont know how yet..
a manual way is to use a card editor like [DataEditorX](https://github.com/247321453/DataEditorX) and copy/paste all cards to a 1 database
but for cards in DM-06+ i havent made databases yet

> because YGOPro-DM is compatible with YGOPro-YGO?

Yes, but only with out any Yugioh cards, your deck must have only Duel Masters cards + 1 Duel Masters Rules card, and it shud work on any Ygopro
except i dont know about the new link rules, i havent updated for them yet

> And images. Do you have this?

Not any more, for copyright and it makes the file too big for ["Download ZIP"](https://github.com/Hello23-Ygopro/ygopro-dm/archive/master.zip) after each update
but heres an example of HQ pics, except video game-only cards : 
http://duelmasters.wikia.com/wiki/DM-01_Base_Set_Gallery_(TCG)
http://duelmasters.wikia.com/wiki/DM-02_Evo-Crushinators_of_Doom_Gallery_(TCG)

**Comment by Hello23-Ygopro** [comment]
https://github.com/Hello23-Ygopro/ygopro-ka/commit/4ebeca4dce93e69945be0f3ff7aca7080f8cd4b7
